# Data Cleaning

# Online Retail Analytics

### Objective

In this notebook, we will clean the dataset by handling:

- Missing values
- Duplicates
- Incorrect data types
- Negative quantities
- Invalid prices
- Cancelled orders

This will prepare the dataset for analysis and modeling.

In [1]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/raw/online_retail_II.csv")

df = pd.read_csv(DATA_PATH)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [2]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [3]:
df_clean = df.dropna(subset=["Customer ID", "Description"])

df_clean.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [4]:
df_clean = df_clean.drop_duplicates()

print(df_clean.duplicated().sum())

0

In [5]:
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

In [6]:
df_clean = df_clean[df_clean["Quantity"] > 0]

In [7]:
df_clean = df_clean[df_clean["Price"] > 0]

In [9]:
df_clean["TotalPrice"] = df_clean["Quantity"] * df_clean["Price"]

In [10]:
print(df_clean.shape)
df_clean.head()

(779425, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [12]:
output_path = Path("../data/processed/cleaned_online_retail.csv")

df_clean.to_csv(output_path, index=False)